export const GET_TECH_NEWS_REQUEST = 'GET_TECH_NEWS_REQUEST';
export const GET_TECH_NEWS_SUCCESS = 'GET_TECH_NEWS_SUCCESS';
export const GET_TECH_NEWS_FAILURE = 'GET_TECH_NEWS_FAILURE';

export const GET_INDIVISUAL_NEWS_DATA_REQUEST =
	'GET_INDIVISUAL_NEWS_DATA_REQUEST';
export const GET_INDIVISUAL_NEWS_DATA_SUCCESS =
	'GET_INDIVISUAL_NEWS_DATA_SUCCESS';
export const GET_INDIVISUAL_NEWS_DATA_FAILURE =
	'GET_INDIVISUAL_NEWS_DATA_FAILURE';
