export const GET_BUSINESSAPI_REQUEST = "GET_BUSINESSAPI_REQUEST "
export const GET_BUSINESSAPI_SUCCESS = "GET_BUSINESSAPI_SUCCESS "
export const GET_BUSINESSAPI_FAILURE = "GET_BUSINESSAPI_FAILURE "

export const GET_BUSINESS_INDIA_REQUEST = "GET_BUSINESS_INDIA_REQUEST "
export const GET_BUSINESS_INDIA_SUCCESS = "GET_BUSINESS_INDIA_SUCCESS "
export const GET_BUSINESS_INDIA_FAILURE = "GET_BUSINESS_INDIA_FAILURE "

export const GET_INTERNATIONAL_SUCCESS = "GET_ECONOMY_SUCCESS "
